;;; refinement-tests.el --- Configurable-default regressions -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)

(ert-deftest config-test/haskell-server-settings-are-project-local ()
  (let ((haskell/server-threads 4)
        (haskell/max-completions 250))
    (should (equal (haskell/server-command)
                   '("haskell-language-server-wrapper" "--lsp" "-j" "4")))
    (should (equal (haskell/eglot-workspace-configuration nil)
                   '(:haskell (:maxCompletions 250)))))
  (let ((haskell/server-threads nil))
    (should (equal (haskell/server-command)
                   '("haskell-language-server-wrapper" "--lsp")))))

(ert-deftest config-test/haskell-does-not-override-server-sorting ()
  (with-temp-buffer
    (cl-letf (((symbol-function 'eglot-ensure) #'ignore))
      (haskell-mode)
      (should-not (local-variable-p 'corfu-sort-override-function)))))

(ert-deftest config-test/shared-buffer-size-policy ()
  (with-temp-buffer
    (insert "12345")
    (let ((buffers/feature-size-limit 5))
      (should-not (buffers/small-p))
      (should (buffers/small-p 6)))
    (let ((buffers/feature-size-limit nil))
      (should (buffers/small-p)))))

(ert-deftest config-test/whitespace-preserves-prose-and-markdown-breaks ()
  (dolist (mode '(text-mode markdown-mode))
    (with-temp-buffer
      (funcall mode)
      (insert "line  \n")
      (emacs/delete-trailing-whitespace-maybe)
      (should (equal (buffer-string) "line  \n")))))

(ert-deftest config-test/whitespace-respects-project-policy ()
  (with-temp-buffer
    (emacs-lisp-mode)
    (insert "code  \n")
    (let ((editor/trim-trailing-whitespace nil))
      (emacs/delete-trailing-whitespace-maybe)
      (should (equal (buffer-string) "code  \n")))
    (emacs/delete-trailing-whitespace-maybe)
    (should (equal (buffer-string) "code\n")))
  (with-temp-buffer
    (text-mode)
    (insert "text  \n")
    (let ((editor/trim-trailing-whitespace t))
      (emacs/delete-trailing-whitespace-maybe)
      (should (equal (buffer-string) "text\n")))))

(ert-deftest config-test/text-layout-keeps-upstream-defaults ()
  (with-temp-buffer
    (text-mode)
    (should bidi-display-reordering)
    (should-not bidi-paragraph-direction)
    (should-not bidi-inhibit-bpa)
    (should-not sentence-end)))

(ert-deftest config-test/javascript-runtime-follows-project-not-buffer-type ()
  (config-test/with-directory
    (with-temp-buffer
      (setq major-mode 'typescript-mode)
      (cl-letf (((symbol-function 'executable-find)
                 (lambda (name) (concat "/bin/" name))))
        (should (equal (javascript--runtime root) "/bin/node"))
        (config-test/file root "bun.lock")
        (should (equal (javascript--runtime root) "/bin/bun"))
        (config-test/file root "deno.json" "{}")
        (should (equal (javascript--runtime root) "/bin/deno"))
        (let ((javascript/runtime 'node))
          (should (equal (javascript--runtime root) "/bin/node")))))))

(ert-deftest config-test/javascript-explicit-runtime-never-silently-falls-back ()
  (let ((javascript/runtime 'bun))
    (cl-letf (((symbol-function 'executable-find) (lambda (_name) nil)))
      (should-error (javascript--runtime default-directory) :type 'user-error))))

(ert-deftest config-test/javascript-project-commands-override-generated-commands ()
  (let ((javascript/run-command "npm run dev")
        (javascript/build-command "npm run build")
        (javascript/check-command "npm test")
        invoked)
    (cl-letf (((symbol-function 'javascript/project-root) (lambda () default-directory))
              ((symbol-function 'compile) (lambda (command) (push command invoked))))
      (javascript/run)
      (javascript/compile)
      (javascript/check)
      (should (equal (reverse invoked) '("npm run dev" "npm run build" "npm test"))))))

(ert-deftest config-test/javascript-debug-settings-are-evaluated-at-launch ()
  (require 'dape)
  (let ((javascript/inspector-port 9333)
        (javascript/browser-url "http://localhost:8080")
        (javascript/debug-adapter-command "custom-js-debug")
        (javascript/deno-permissions '("--allow-read")))
    (should (equal (javascript/deno-debug-arguments)
                   ["run" "--inspect-wait=127.0.0.1:9333" "--allow-read"]))
    (should (equal (dape-config-get (alist-get 'javascript-chrome dape-configs) :url)
                   "http://localhost:8080"))
    (should (equal (dape-config-get (alist-get 'javascript-node dape-configs) 'command)
                   "custom-js-debug"))
    (should (= (dape-config-get (alist-get 'typescript-deno dape-configs)
                               :attachSimplePort) 9333)))
  (let ((javascript/deno-permissions nil))
    (should-not (member "--allow-all" (append (javascript/deno-debug-arguments) nil)))))

(ert-deftest config-test/eldoc-uses-public-hover-mode ()
  (require 'eldoc-box)
  (with-temp-buffer
    (emacs-lisp-mode)
    (let ((eldoc-display-functions '(eldoc-display-in-echo-area))
          enabled)
      (cl-letf (((symbol-function 'display-graphic-p) (lambda (&optional _display) t))
                ((symbol-function 'eldoc-box-hover-at-point-mode)
                 (lambda (argument) (setq enabled argument))))
        (completion/eldoc-popup-maybe)
        (should eldoc-mode)
        (should (= enabled 1))
        (should (equal eldoc-display-functions '(eldoc-display-in-echo-area)))))))

(ert-deftest config-test/eldoc-terminal-keeps-built-in-display ()
  (with-temp-buffer
    (emacs-lisp-mode)
    (let (requested)
      (cl-letf (((symbol-function 'display-graphic-p) (lambda (&optional _display) nil))
                ((symbol-function 'eldoc-print-current-symbol-info)
                 (lambda (&optional interactive) (setq requested interactive))))
        (completion/eldoc-popup-maybe)
        (should eldoc-mode)
        (completion/eldoc-show-at-point)
        (should requested)))))

(ert-deftest config-test/theme-workaround-is-scoped-and-restored ()
  (let ((original (symbol-function 'custom-theme-set-faces))
        received)
    (cl-letf (((symbol-function 'load-theme)
               (lambda (&rest _ignored)
                 (custom-theme-set-faces 'unrelated '(example ((t (:foreground nil)))))
                 (should (equal received '(unrelated (example ((t (:foreground nil)))))))
                 (custom-theme-set-faces 'gruber-darker '(example ((t (:foreground nil)))))
                 (should (equal received '(gruber-darker (example ((t (:foreground unspecified)))))))
                 (error "Load failed")))
              ((symbol-function 'custom-theme-set-faces)
               (lambda (&rest args) (setq received args))))
      (let ((before (symbol-function 'custom-theme-set-faces)))
        (should-error (theme/load-gruber-darker))
        (should (eq (symbol-function 'custom-theme-set-faces) before))))
    (should (eq (symbol-function 'custom-theme-set-faces) original))))

(ert-deftest config-test/mount-path-policy-follows-current-customization ()
  (let ((mounts/android-mount-directory "/tmp/example-phone/")
        (mounts/mac-mini-mount-directory "/tmp/example-share/")
        (locations/additional-unreliable-directories nil))
    (cl-letf (((symbol-function 'file-truename)
               (lambda (&rest _) (ert-fail "Mount predicate performed filesystem I/O"))))
      (should (locations/unreliable-path-p "/tmp/example-phone"))
      (should (locations/unreliable-path-p "/tmp/example-share/book.epub"))
      (should-not (locations/unreliable-path-p "/tmp/example-share-other/file"))
      (should (memq #'locations/unreliable-path-p recentf-exclude)))))

(ert-deftest config-test/mount-destination-uses-remote-home-not-local-expansion ()
  (let ((mounts/mac-mini-host "other-host")
        (mounts/mac-mini-remote-home-directory "~/"))
    (cl-letf (((symbol-function 'mounts/mac-mini-relative-path)
               (lambda (_path) "docs")))
      (should (equal (mounts/mac-mini-rsync-destination "ignored")
                     "/ssh:other-host:~/docs/")))))

(ert-deftest config-test/desktop-commands-preserve-file-arguments ()
  (let (started)
    (cl-letf (((symbol-function 'executable-find) (lambda (name) (concat "/bin/" name)))
              ((symbol-function 'dirvish--local-files)
               (lambda () '("/tmp/file with spaces" "/tmp/$(not-a-command)")))
              ((symbol-function 'start-process) (lambda (&rest args) (setq started args))))
      (dirvish/desktop-action '("other-manager" "--new-window"))
      (should (equal started '("other-manager" nil "/bin/other-manager" "--new-window"
                               "/tmp/file with spaces" "/tmp/$(not-a-command)"))))))

(ert-deftest config-test/mount-command-overrides-preserve-arguments ()
  (cl-letf (((symbol-function 'executable-find) (lambda (_name) "/bin/helper")))
    (should (equal (mounts/resolve-command '("helper" "--profile" "phone"))
                   '("/bin/helper" "--profile" "phone"))))
  (should-error (mounts/resolve-command nil) :type 'user-error))

(ert-deftest config-test/pair-activation-is-configurable ()
  (with-temp-buffer
    (text-mode)
    (let ((pairs/enabled-modes '(text-mode)))
      (pairs/enable)
      (should smartparens-mode)))
  (with-temp-buffer
    (let ((pairs/enabled-modes nil))
      (emacs-lisp-mode)
      (should-not smartparens-mode))))

(ert-deftest config-test/lsp-resolution-ignores-other-jsonrpc-connections ()
  (let ((item (list :data 1)))
    (cl-letf (((symbol-function 'eglot-current-server) (lambda () 'eglot-server)))
      (lsp/completion-resolve-command
       (lambda (&rest _) '(:command (:command "other-command")))
       'other-connection :completionItem/resolve item)
      (should-not (plist-member item :command)))))

(ert-deftest config-test/lsp-completion-bridge-can-be-disabled ()
  (unwind-protect
      (let ((lsp/completion-command-support nil))
        (lsp/configure-completion-commands)
        (should-not (advice-member-p #'lsp/completion-command-filter 'eglot-completion-at-point))
        (should-not (advice-member-p #'lsp/completion-resolve-command 'jsonrpc-request)))
    (lsp/configure-completion-commands))
  (should-not (advice-member-p #'lsp/completion-resolve-command 'eglot--request)))

(provide 'refinement-tests)
;;; refinement-tests.el ends here
