;;; refinement-tests.el --- Configurable-default regressions -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)

(ert-deftest config-test/haskell-server-settings-are-project-local ()
  (let ((haskell/server-threads 4)
        (haskell/max-completions 250))
    (should (equal (haskell/server-command)
                   '("haskell-language-server-wrapper" "--lsp" "-j" "4")))
    (should (equal (haskell/eglot-workspace-configuration nil)
                   '(:haskell (:maxCompletions 250)))))
  (let ((haskell/server-threads nil))
    (should (equal (haskell/server-command)
                   '("haskell-language-server-wrapper" "--lsp")))))

(ert-deftest config-test/haskell-does-not-override-server-sorting ()
  (with-temp-buffer
    (cl-letf (((symbol-function 'eglot-ensure) #'ignore))
      (haskell-mode)
      (should-not (local-variable-p 'corfu-sort-override-function)))))

(ert-deftest config-test/shared-buffer-size-policy ()
  (with-temp-buffer
    (insert "12345")
    (let ((buffers/feature-size-limit 5))
      (should-not (buffers/small-p))
      (should (buffers/small-p 6)))
    (let ((buffers/feature-size-limit nil))
      (should (buffers/small-p)))))

(ert-deftest config-test/whitespace-preserves-prose-and-markdown-breaks ()
  (dolist (mode '(text-mode markdown-mode))
    (with-temp-buffer
      (funcall mode)
      (insert "line  \n")
      (emacs/delete-trailing-whitespace-maybe)
      (should (equal (buffer-string) "line  \n")))))

(ert-deftest config-test/whitespace-respects-project-policy ()
  (with-temp-buffer
    (emacs-lisp-mode)
    (insert "code  \n")
    (let ((editor/trim-trailing-whitespace nil))
      (emacs/delete-trailing-whitespace-maybe)
      (should (equal (buffer-string) "code  \n")))
    (emacs/delete-trailing-whitespace-maybe)
    (should (equal (buffer-string) "code\n")))
  (with-temp-buffer
    (text-mode)
    (insert "text  \n")
    (let ((editor/trim-trailing-whitespace t))
      (emacs/delete-trailing-whitespace-maybe)
      (should (equal (buffer-string) "text\n")))))

(ert-deftest config-test/text-layout-keeps-upstream-defaults ()
  (with-temp-buffer
    (text-mode)
    (should bidi-display-reordering)
    (should-not bidi-paragraph-direction)
    (should-not bidi-inhibit-bpa)
    (should-not sentence-end)))

(ert-deftest config-test/javascript-runtime-follows-project-not-buffer-type ()
  (config-test/with-directory
    (with-temp-buffer
      (setq major-mode 'typescript-mode)
      (cl-letf (((symbol-function 'executable-find)
                 (lambda (name) (concat "/bin/" name))))
        (should (equal (javascript--runtime root) "/bin/node"))
        (config-test/file root "bun.lock")
        (should (equal (javascript--runtime root) "/bin/bun"))
        (config-test/file root "deno.json" "{}")
        (should (equal (javascript--runtime root) "/bin/deno"))
        (let ((javascript/runtime 'node))
          (should (equal (javascript--runtime root) "/bin/node")))))))

(ert-deftest config-test/javascript-explicit-runtime-never-silently-falls-back ()
  (let ((javascript/runtime 'bun))
    (cl-letf (((symbol-function 'executable-find) (lambda (_name) nil)))
      (should-error (javascript--runtime default-directory) :type 'user-error))))

(ert-deftest config-test/javascript-project-commands-override-generated-commands ()
  (let ((javascript/run-command "npm run dev")
        (javascript/build-command "npm run build")
        (javascript/check-command "npm test")
        invoked)
    (cl-letf (((symbol-function 'javascript/project-root) (lambda () default-directory))
              ((symbol-function 'compile) (lambda (command) (push command invoked))))
      (javascript/run)
      (javascript/compile)
      (javascript/check)
      (should (equal (reverse invoked) '("npm run dev" "npm run build" "npm test"))))))

(ert-deftest config-test/javascript-debug-settings-are-evaluated-at-launch ()
  (require 'dape)
  (let ((javascript/inspector-port 9333)
        (javascript/browser-url "http://localhost:8080")
        (javascript/debug-adapter-command "custom-js-debug")
        (javascript/deno-permissions '("--allow-read")))
    (should (equal (javascript/deno-debug-arguments)
                   ["run" "--inspect-wait=127.0.0.1:9333" "--allow-read"]))
    (should (equal (dape-config-get (alist-get 'javascript-chrome dape-configs) :url)
                   "http://localhost:8080"))
    (should (equal (dape-config-get (alist-get 'javascript-node dape-configs) 'command)
                   "custom-js-debug"))
    (should (= (dape-config-get (alist-get 'typescript-deno dape-configs)
                               :attachSimplePort) 9333)))
  (let ((javascript/deno-permissions nil))
    (should-not (member "--allow-all" (append (javascript/deno-debug-arguments) nil)))))

(ert-deftest config-test/eldoc-uses-public-hover-mode ()
  (require 'eldoc-box)
  (with-temp-buffer
    (emacs-lisp-mode)
    (let ((eldoc-display-functions '(eldoc-display-in-echo-area))
          enabled)
      (cl-letf (((symbol-function 'display-graphic-p) (lambda (&optional _display) t))
                ((symbol-function 'eldoc-box-hover-at-point-mode)
                 (lambda (argument) (setq enabled argument))))
        (completion/eldoc-popup-maybe)
        (should eldoc-mode)
        (should (= enabled 1))
        (should (equal eldoc-display-functions '(eldoc-display-in-echo-area)))))))

(ert-deftest config-test/eldoc-terminal-keeps-built-in-display ()
  (with-temp-buffer
    (emacs-lisp-mode)
    (let (requested)
      (cl-letf (((symbol-function 'display-graphic-p) (lambda (&optional _display) nil))
                ((symbol-function 'eldoc-print-current-symbol-info)
                 (lambda (&optional interactive) (setq requested interactive))))
        (completion/eldoc-popup-maybe)
        (should eldoc-mode)
        (completion/eldoc-show-at-point)
        (should requested)))))

(ert-deftest config-test/completion-balanced-performance-defaults ()
  (require 'corfu-auto)
  (require 'cape)
  (should corfu-auto)
  (should (= corfu-auto-prefix 2))
  (should (= corfu-auto-delay 0.2))
  (should (equal corfu-popupinfo-delay '(0.5 . 0.2)))
  (should (eq cape-dabbrev-buffer-function #'current-buffer)))

(ert-deftest config-test/completion-manual-dabbrev-stays-buffer-local ()
  (require 'cape)
  (let ((other (generate-new-buffer " *completion scan test*")))
    (unwind-protect
        (progn
          (with-current-buffer other
            (text-mode)
            (insert "configperfremote"))
          (with-temp-buffer
            (text-mode)
            (insert "configperflocal\nc")
            ;; Manual completion still works with a one-character prefix.
            (let* ((completion-at-point-functions '(cape-dabbrev))
                   matches
                   (completion-in-region-function
                    (lambda (beg end table &optional predicate)
                      (setq matches
                            (all-completions (buffer-substring beg end)
                                             table predicate))
                      t)))
              (should (completion-at-point))
              (should (member "configperflocal" matches))
              (should-not (member "configperfremote" matches)))
            ;; The same fixture exposes the cross-buffer candidate when opted in.
            (let* ((cape-dabbrev-buffer-function #'cape-same-mode-buffers)
                   (capf (cape-dabbrev)))
              (should (member "configperfremote"
                              (all-completions "c" (nth 2 capf)))))))
      (kill-buffer other))))

(ert-deftest config-test/completion-colors-follow-theme-changes ()
  (require 'corfu-popupinfo)
  (deftheme config-test-completion-palette "Temporary completion palette.")
  (let ((original-background
         (face-attribute 'corfu-default :background nil 'default)))
    (unwind-protect
        (dolist (palette '(("#181818" "#e4e4ef" "#282828" "#484848" "#101010")
                           ("#ffffff" "#202020" "#eeeeee" "#cccccc" "#dddddd")))
          (pcase-let ((`(,background ,foreground ,selection ,bar ,border) palette))
            (custom-theme-set-faces
             'config-test-completion-palette
             `(default ((t (:background ,background :foreground ,foreground))))
             `(highlight ((t (:background ,selection :foreground unspecified))))
             `(region ((t (:background ,bar))))
             `(fringe ((t (:background ,border))))))
          (enable-theme 'config-test-completion-palette)
          (dolist (entry '((corfu-default . default)
                           (corfu-popupinfo . default)
                           (corfu-current . highlight)
                           (corfu-bar . region)
                           (corfu-border . fringe)))
            (should (equal (face-attribute (car entry) :background nil 'default)
                           (face-attribute (cdr entry) :background nil 'default))))
          (dolist (face '(corfu-default corfu-popupinfo corfu-current))
            (should (equal (face-attribute face :foreground nil 'default)
                           (face-attribute 'default :foreground))))
          ;; Corfu's scrollbar renderer reads this attribute directly.
          (should (equal (face-attribute 'corfu-bar :background)
                         (face-background 'region nil t)))
          (should (eq (face-attribute 'corfu-current :extend) t)))
      (disable-theme 'config-test-completion-palette))
    (should (equal (face-attribute 'corfu-default :background nil 'default)
                   original-background))
    (should (equal (face-attribute 'corfu-bar :background)
                   (face-background 'region nil t)))))

(ert-deftest config-test/completion-preserves-theme-specific-faces ()
  (deftheme config-test-completion-native "Temporary native Corfu palette.")
  (let ((fallback (face-attribute 'corfu-current :background nil 'default)))
    (unwind-protect
        (progn
          (custom-theme-set-faces
           'config-test-completion-native
           '(corfu-current ((t (:background "#123456" :foreground "#abcdef"))))
           '(corfu-popupinfo ((t (:background "#654321")))))
          (enable-theme 'config-test-completion-native)
          (should (equal (face-attribute 'corfu-current :background) "#123456"))
          (should (equal (face-attribute 'corfu-current :foreground) "#abcdef"))
          (should (equal (face-attribute 'corfu-popupinfo :background) "#654321")))
      (disable-theme 'config-test-completion-native))
    (should (equal (face-attribute 'corfu-current :background nil 'default)
                   fallback))))

(ert-deftest config-test/theme-workaround-is-scoped-and-restored ()
  (let ((original (symbol-function 'custom-theme-set-faces))
        received)
    (cl-letf (((symbol-function 'load-theme)
               (lambda (&rest _ignored)
                 (custom-theme-set-faces 'unrelated '(example ((t (:foreground nil)))))
                 (should (equal received '(unrelated (example ((t (:foreground nil)))))))
                 (custom-theme-set-faces 'gruber-darker '(example ((t (:foreground nil)))))
                 (should (equal received '(gruber-darker (example ((t (:foreground unspecified)))))))
                 (error "Load failed")))
              ((symbol-function 'custom-theme-set-faces)
               (lambda (&rest args) (setq received args))))
      (let ((before (symbol-function 'custom-theme-set-faces)))
        (should-error (theme/load-gruber-darker))
        (should (eq (symbol-function 'custom-theme-set-faces) before))))
    (should (eq (symbol-function 'custom-theme-set-faces) original))))

(ert-deftest config-test/mount-path-policy-follows-current-customization ()
  (let ((mounts/android-mount-directory "/tmp/example-phone/")
        (mounts/mac-mini-mount-directory "/tmp/example-share/")
        (locations/additional-unreliable-directories nil))
    (cl-letf (((symbol-function 'file-truename)
               (lambda (&rest _) (ert-fail "Mount predicate performed filesystem I/O"))))
      (should (locations/unreliable-path-p "/tmp/example-phone"))
      (should (locations/unreliable-path-p "/tmp/example-share/book.epub"))
      (should-not (locations/unreliable-path-p "/tmp/example-share-other/file"))
      (should (memq #'locations/unreliable-path-p recentf-exclude)))))

(ert-deftest config-test/mount-destination-uses-remote-home-not-local-expansion ()
  (let ((mounts/mac-mini-host "other-host")
        (mounts/mac-mini-remote-home-directory "~/"))
    (cl-letf (((symbol-function 'mounts/mac-mini-relative-path)
               (lambda (_path) "docs")))
      (should (equal (mounts/mac-mini-rsync-destination "ignored")
                     "/ssh:other-host:~/docs/")))))

(ert-deftest config-test/desktop-commands-preserve-file-arguments ()
  (let (started)
    (cl-letf (((symbol-function 'executable-find) (lambda (name) (concat "/bin/" name)))
              ((symbol-function 'dirvish--local-files)
               (lambda () '("/tmp/file with spaces" "/tmp/$(not-a-command)")))
              ((symbol-function 'start-process) (lambda (&rest args) (setq started args))))
      (dirvish/desktop-action '("other-manager" "--new-window"))
      (should (equal started '("other-manager" nil "/bin/other-manager" "--new-window"
                               "/tmp/file with spaces" "/tmp/$(not-a-command)"))))))

(ert-deftest config-test/mount-command-overrides-preserve-arguments ()
  (cl-letf (((symbol-function 'executable-find) (lambda (_name) "/bin/helper")))
    (should (equal (mounts/resolve-command '("helper" "--profile" "phone"))
                   '("/bin/helper" "--profile" "phone"))))
  (should-error (mounts/resolve-command nil) :type 'user-error))

(ert-deftest config-test/pair-activation-is-configurable ()
  (with-temp-buffer
    (text-mode)
    (let ((pairs/enabled-modes '(text-mode)))
      (pairs/enable)
      (should smartparens-mode)))
  (with-temp-buffer
    (let ((pairs/enabled-modes nil))
      (emacs-lisp-mode)
      (should-not smartparens-mode))))

(ert-deftest config-test/lsp-resolution-ignores-other-jsonrpc-connections ()
  (let ((item (list :data 1)))
    (cl-letf (((symbol-function 'eglot-current-server) (lambda () 'eglot-server)))
      (lsp/completion-resolve-command
       (lambda (&rest _) '(:command (:command "other-command")))
       'other-connection :completionItem/resolve item)
      (should-not (plist-member item :command)))))

(ert-deftest config-test/lsp-completion-bridge-can-be-disabled ()
  (unwind-protect
      (let ((lsp/completion-command-support nil))
        (lsp/configure-completion-commands)
        (should-not (advice-member-p #'lsp/completion-command-filter 'eglot-completion-at-point))
        (should-not (advice-member-p #'lsp/completion-resolve-command 'jsonrpc-request)))
    (lsp/configure-completion-commands))
  (should-not (advice-member-p #'lsp/completion-resolve-command 'eglot--request)))

(ert-deftest config-test/dirvish-observer-uses-public-handler-and-filter ()
  (require 'dirvish-yank)
  (require 'task-dashboard)
  (let ((processes '(existing)) tracked)
    (cl-letf (((symbol-function 'process-list) (lambda () processes))
              ((symbol-function 'process-filter)
               (lambda (process) (if (eq process 'new-dirvish)
                                    #'dirvish-yank-proc-filter #'ignore)))
              ((symbol-function 'task-dashboard-track-process)
               (lambda (process &rest _args) (push process tracked))))
      (should (eq (dirvish/track-yank
                   (lambda (&rest _args)
                     (setq processes '(new-dirvish unrelated existing)) 'original-result)
                   'copy '("file") "/tmp/")
                  'original-result))
      (should (equal tracked '(new-dirvish))))
    (should-not (advice-member-p 'dirvish/track-yank-start 'dirvish-yank--start-proc))))

(ert-deftest config-test/dirvish-progress-uses-package-property-accessor ()
  (let ((buffer (generate-new-buffer " *dirvish progress test*")))
    (unwind-protect
        (progn
          (with-current-buffer buffer (dirvish-prop :yank-percent "42%"))
          (cl-letf (((symbol-function 'task-dashboard-task-process) (lambda (_task) 'process))
                    ((symbol-function 'process-buffer) (lambda (_process) buffer)))
            (should (= (dirvish--yank-progress 'task) 42))))
      (kill-buffer buffer))))

(ert-deftest config-test/dirvish-task-observers-can-be-disabled ()
  (require 'dirvish-yank)
  (unwind-protect
      (let ((dirvish/task-tracking nil))
        (dirvish/configure-task-tracking)
        (should-not (advice-member-p #'dirvish/track-yank 'dirvish-yank-default-handler)))
    (dirvish/configure-task-tracking)))

(ert-deftest config-test/haskell-settings-use-directory-local-workspace-context ()
  (config-test/with-directory
    (config-test/file
     root ".dir-locals.el"
     "((haskell-mode . ((haskell/server-threads . 3) (haskell/max-completions . 123))))")
    (with-temp-buffer
      (setq major-mode 'haskell-mode)
      (hack-dir-local-variables-non-file-buffer)
      (should (equal (haskell/server-command)
                     '("haskell-language-server-wrapper" "--lsp" "-j" "3")))
      (should (equal (lsp/workspace-configuration 'unused-server)
                     '(:haskell (:maxCompletions 123)))))))

(ert-deftest config-test/dirvish-real-copy-retains-task-observation ()
  (require 'dirvish-yank)
  (require 'task-dashboard)
  (config-test/with-directory
    (let* ((source (config-test/file root "source.txt" "temporary test content"))
           (destination (expand-file-name "destination/" root))
           (task-dashboard--tasks nil)
           (dirvish-yank-log-buffers nil)
           (override-enabled dirvish-override-dired-mode)
           (callback-count 0)
           callback-succeeded dired-buffer process
           (observer (lambda (original &rest arguments)
                       (cl-incf callback-count)
                       (prog1 (apply original arguments)
                         (setq callback-succeeded t)))))
      (make-directory destination)
      (unwind-protect
          (cl-letf (((symbol-function 'task-dashboard--notify) #'ignore))
            ;; A real, file-backed Dired listing lets the package's sentinel
            ;; revert its source buffer.  No temporary non-file buffer and no
            ;; stubbing of the package's callback/refresh behavior.
            (dirvish-override-dired-mode -1)
            (setq dired-buffer (dired-noselect root))
            (when override-enabled (dirvish-override-dired-mode 1))
            (advice-add 'dirvish-yank-proc-sentinel :around observer)
            (with-current-buffer dired-buffer
              (dirvish-yank-default-handler 'dired-copy-file (list source) destination)
              (should (= (length task-dashboard--tasks) 1))
              (let* ((task (car task-dashboard--tasks))
                     (deadline (+ (float-time) 15)))
                (setq process (task-dashboard-task-process task))
                (while (and (process-live-p process) (< (float-time) deadline))
                  (accept-process-output process 0.1))
                (should-not (process-live-p process))
                (should (= (process-exit-status process) 0))
                (should (eq (task-dashboard-task-status task) 'completed))
                (should (= callback-count 1))
                (should callback-succeeded)
                (should (equal (with-temp-buffer
                                 (insert-file-contents
                                  (expand-file-name "source.txt" destination))
                                 (buffer-string))
                               "temporary test content")))))
        (when (and process (process-live-p process)) (delete-process process))
        (advice-remove 'dirvish-yank-proc-sentinel observer)
        (dirvish-override-dired-mode (if override-enabled 1 -1))
        (when (buffer-live-p dired-buffer) (kill-buffer dired-buffer))
        (dolist (task task-dashboard--tasks)
          (when-let* ((buffer (task-dashboard-task-output-buffer task))
                      ((buffer-live-p buffer)))
            (kill-buffer buffer)))
        (dolist (buffer dirvish-yank-log-buffers)
          (when (buffer-live-p buffer) (kill-buffer buffer)))))))

(ert-deftest config-test/fonts-use-first-installed-fallback ()
  (cl-letf (((symbol-function 'find-font)
             (lambda (spec frame)
               (should (eq frame 'test-frame))
               (eq (font-get spec :family) 'Installed))))
    (should (equal (appearance--available-font '("Missing" "Installed" "Other")
                                              'test-frame)
                   "Installed"))
    (should-not (appearance--available-font '("Missing") 'test-frame))))

(ert-deftest config-test/fonts-do-not-query-terminal-frames ()
  (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) nil))
            ((symbol-function 'find-font)
             (lambda (&rest _) (ert-fail "Font query on terminal frame"))))
    (appearance/apply-fonts)))

(ert-deftest config-test/fonts-apply-preferences-to-the-requested-gui-frame ()
  (let ((appearance/font-families '("Installed"))
        (appearance/font-height 140)
        (appearance/script-font-families '((emoji "Installed")))
        faces fontset)
    (cl-letf (((symbol-function 'display-graphic-p)
               (lambda (frame) (eq frame 'test-frame)))
              ((symbol-function 'find-font) (lambda (&rest _) t))
              ((symbol-function 'set-face-attribute)
               (lambda (&rest arguments) (push arguments faces)))
              ((symbol-function 'set-fontset-font)
               (lambda (&rest arguments) (setq fontset arguments))))
      (appearance/apply-fonts 'test-frame)
      (should (member '(default test-frame :family "Installed") faces))
      (should (member '(default test-frame :height 140) faces))
      (should-not (car fontset))
      (should (eq (nth 1 fontset) 'emoji))
      (should (eq (font-get (nth 2 fontset) :family) 'Installed))
      (should (eq (nth 3 fontset) 'test-frame))
      (should (eq (nth 4 fontset) 'prepend)))))

(ert-deftest config-test/fonts-preserve-defaults-when-no-family-is-installed ()
  (let ((appearance/font-families '("Missing"))
        (appearance/font-height nil)
        (appearance/script-font-families '((emoji "Missing"))))
    (cl-letf (((symbol-function 'display-graphic-p) (lambda (&rest _) t))
              ((symbol-function 'find-font) (lambda (&rest _) nil))
              ((symbol-function 'set-face-attribute)
               (lambda (&rest _) (ert-fail "Changed default font")))
              ((symbol-function 'set-fontset-font)
               (lambda (&rest _) (ert-fail "Changed fontset"))))
      (appearance/apply-fonts))))

(ert-deftest config-test/hl-line-fallback-follows-theme ()
  (deftheme config-test-line-palette "Temporary line highlight palette.")
  (unwind-protect
      (dolist (color '("#282828" "#eeeeee"))
        (custom-theme-set-faces
         'config-test-line-palette
         `(highlight ((t (:background ,color)))))
        (enable-theme 'config-test-line-palette)
        (should (equal (face-background 'hl-line nil t) color)))
    (disable-theme 'config-test-line-palette)))

(provide 'refinement-tests)
;;; refinement-tests.el ends here
